ALTER TABLE span DROP COLUMN span_attributes;
ALTER TABLE span DROP COLUMN resource_attributes;
ALTER TABLE span DROP COLUMN scope_attributes;
ALTER TABLE span ALTER COLUMN latency SET DATA TYPE DOUBLE PRECISION;