# Default values for zk-scenario-manager.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  dockerBase: "zerokai"

obfuscate: false

replicaCount: 1

serviceConfigs:
  logs:
    color: true
    level: DEBUG

workLoadTtl: 900
workLoadTickerDuration: 60
otelQueueWorkerCount: 4

redis:
  host: redis.zk-client.svc.cluster.local
  port: 6379
  readTimeout: 20
  dbs:
    filtered_traces: 1
    scenarios: 2
    traces: 3
    executor_attr: 4
    pod_details: 7
    error_details: 8

zkScenarioManager:
  resources:
    limits:
      cpu: 1
      memory: 1024Mi
    requests:
      cpu: 512m
      memory: 512Mi

image:
  repo: "zk-scenario-manager"
  tag: "latest"
  imagePullPolicy: Always
  migrationRestartPolicy: Never
  migrationRepo: "zk-scenario-manager-migration"
  migrationTag: "latest"

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

ports:
- port: 80
  protocol: TCP
  targetPort: 80

