redis:
  host: 127.0.0.1
  password: "FuH0jXb9kt"
  port: 6379
  dbs:
    filtered_traces: 1
    scenarios: 2
    traces: 3
    executor_attr: 4
    pod_details: 7
    error_details: 8
  readTimeout: 20
postgres:
  host: 127.0.0.1
  port: 5432
  user: "postgres"
  password: "eo1Mgtm6HI"
  dbname: "pl"
logs:
  color: true
  level: DEBUG
scenarioConfig:
  redisRuleSetCount: 12
  processingIntervalInSeconds: 10
  vzCloudAddr: "px.devcloud01.getanton.com:443"
  vzClusterId: "351c0b80-e25c-4dbc-9fc6-94d69dfaf0ad"
  vzClusterKey: "px-api-e0593597-de51-44cd-bc72-6cbdb881b2be"
server:
  host: localhost
  port: 80