redis:
  host: 127.0.0.1
  port: 6379
  dbs:
    traces: 1
    otel: 3
    scenarios: 6
  readTimeout: 20
postgres:
  host: 127.0.0.1
  port: 5432
  user: "postgres"
  password: "eo1Mgtm6HI"
  dbname: "pl"
logs:
  color: true
  level: DEBUG
scenarioConfig:
  redisRuleSetCount: 12