redis:
  host: 127.0.0.1
  password: "kj1p9v5tkB"
  port: 6379
  dbs:
    filtered_traces: 1
    scenarios: 2
    traces: 3
    executor_attr: 4
    pod_details: 7
    error_details: 8
  readTimeout: 20
postgres:
  host: 127.0.0.1
  port: 5432
  user: "postgres"
  password: "eo1Mgtm6HI"
  dbname: "pl"
  max_connections: 5
  max_idle_connections: 5
  connection_max_lifetime_in_minutes: 10
logs:
  color: true
  level: DEBUG
scenarioConfig:
  redisRuleSetCount: 12
  processingIntervalInSeconds: 10
  ebpfSchemaVersion: "0.1.1-alpha"
  vzCloudAddr: "px.loadcloud01.getanton.com:443"
  vzClusterId: "81fd3738-5cf2-4006-b45f-64f854d0c986"
  vzClusterKey: "px-api-f8d4bc05-381d-469b-ab54-82b7128e58ee"
server:
  host: localhost
  port: 80
