redis:
  host: 127.0.0.1
  port: 6379
  dbs:
    traces: 1
    scenarios: 2
    otel: 3
    ip: 5
    exceptions: 8
  readTimeout: 20
postgres:
  host: 127.0.0.1
  port: 5432
  user: "postgres"
  password: "eo1Mgtm6HI"
  dbname: "pl"
logs:
  color: true
  level: DEBUG
scenarioConfig:
  redisRuleSetCount: 12
  processingIntervalInSeconds: 10
  vzCloudAddr: "px.devcloud01.getanton.com:443"
  vzClusterId: "6c213fb3-a773-4d8b-b0ad-d6e1b720da6f"
  vzClusterKey: "px-api-e0593597-de51-44cd-bc72-6cbdb881b2be"
server:
  host: localhost
  port: 80