redis:
  host: 127.0.0.1
  password: "7qWwxfGN98"
  port: 6379
  dbs:
    filtered_traces: 1
    scenarios: 2
    traces: 3
    executor_attr: 4
    pod_details: 7
    error_details: 8
  readTimeout: 20
postgres:
  host: 127.0.0.1
  port: 5432
  user: "postgres"
  password: "eo1Mgtm6HI"
  dbname: "pl"
  max_connections: 5
  max_idle_connections: 5
  connection_max_lifetime_in_minutes: 10
logs:
  color: true
  level: DEBUG
scenarioConfig:
  redisRuleSetCount: 12
  processingIntervalInSeconds: 10
  ebpfSchemaVersion: "0.1.1-alpha"
  vzCloudAddr: "px.sandbox.zerok.dev:443"
  vzClusterId: "56c86acd-87c4-40d2-afa2-8f02b1c5e398"
  vzClusterKey: "px-api-16ca3a6b-ad70-4f5a-9e08-4d4e7a7bcae9"
server:
  host: localhost
  port: 80
