redis:
  host: 127.0.0.1
  password: "eKbbxAn8qr"
  port: 6379
  dbs:
    filtered_traces: 1
    scenarios: 2
    traces: 3
    executor_attr: 4
    pod_details: 7
    error_details: 8
    resource_and_scope_attr: 5
  readTimeout: 20
scenarioConfig:
  processingIntervalInSeconds: 10
logs:
  color: true
  level: DEBUG
server:
  host: localhost
  port: 80
workLoad:
  ttl: 900
  tickerDuration: 60
exporter:
  host: opentelemetry-collector.opentelemetry-operator-system.svc.cluster.local
  port: 4319
