redis:
  host: 127.0.0.1
  password: "FuH0jXb9kt"
  port: 6379
  dbs:
    filtered_traces: 1
    scenarios: 2
    traces: 3
    executor_attr: 4
    pod_details: 7
    error_details: 8
  readTimeout: 20
postgres:
  host: 127.0.0.1
  port: 5432
  user: "postgres"
  password: "eo1Mgtm6HI"
  dbname: "pl"
  max_connections: 5
  max_idle_connections: 5
  connection_max_lifetime_in_minutes: 10
logs:
  color: true
  level: DEBUG
scenarioConfig:
  redisRuleSetCount: 12
  processingIntervalInSeconds: 10
  ebpfSchemaVersion: "0.1.1-alpha"
  vzCloudAddr: "px.devcloud01.getanton.com:443"
  vzClusterId: "f14c39ad-8796-40a4-8460-b5411b10c1df"
  vzClusterKey: "px-api-3a8352dc-34f6-44d6-991d-f4a22b9ec6b1"
server:
  host: localhost
  port: 80
