apiVersion: v1
kind: Service
metadata:
  name: {{ include "zk-scenario-manager.fullname" . }}
  labels:
  {{- include "zk-scenario-manager.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: zk-scenario-manager
    app.kubernetes.io/name: zk-scenario-manager
  ports:
  {{- .Values.ports | toYaml | nindent 2 -}}