apiVersion: v1
data:
  config.yaml: |-
    redis:
      host: redis-master.zk-client.svc.cluster.local
      port: 6379
      readTimeout: 20
      dbs:     
        traces: 1
        otel: 3
        scenarios: 6
    postgres:
      host: postgres-postgresql.zk-client.svc.cluster.local
      port: 5432
      user: "postgres"
      password: "eo1Mgtm6HI"
      dbname: "pl"
    server:
      host: 0.0.0.0
      port: 80
    scenarioConfig:
      redisRuleSetCount: 12
      processingIntervalInSeconds: 300
kind: ConfigMap
metadata:
  name: zk-scenario-manager