apiVersion: apps/v1
kind: Deployment
metadata:
  name: zk-scenario-manager
  labels:
    app: zk-scenario-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zk-scenario-manager
  template:
    metadata:
      labels:
        app: zk-scenario-manager
    spec:
      volumes:
        - name: config
          configMap:
            name: zk-scenario-manager
      containers:
        - name: zk-scenario-manager
          image: zk-scenario-manager:1.0
          imagePullPolicy: Never
          resources:
            limits:
              cpu: 200m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 64Mi
          volumeMounts:
            - name: config
              mountPath: /zk/config
          readinessProbe:
            httpGet:
              path: /healthz
              port: 80
            successThreshold: 3
          env: # Setting Enviornmental Variables
            - name: PL_POSTGRES_PASSWORD # Setting Database password from Secret
              valueFrom:
                secretKeyRef:
                  name: postgres-postgresql
                  key: postgres-password

---
apiVersion: v1
data:
  config.yaml: |+
    redis:
      host: redis.zk-client.svc.cluster.local
      port: 6379
      readTimeout: 20
      dbs:     
        traces: 1
        otel: 3
        scenarios: 6
    postgres:
      host: postgres-postgresql.zk-client.svc.cluster.local
      port: 5432
      user: "postgres"
      password: "eo1Mgtm6HI"
      dbname: "pl"
kind: ConfigMap
metadata:
  name: zk-scenario-manager
