apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
  labels:
    app: order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      volumes:
        - name: config
          configMap:
            name: zk-scenario-manager
      containers:
        - name: zk-scenario-manager
          image: zk-scenario-manager:1.0
          imagePullPolicy: Never
          resources:
            limits:
              cpu: 200m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 64Mi
          volumeMounts:
            - name: config
              mountPath: /zk/config
          readinessProbe:
            httpGet:
              path: /healthz
              port: 80
            successThreshold: 3

---
apiVersion: v1
data:
  config.yaml: |+
    redis:
      host: redis.zk-client.svc.cluster.local
      port: 6379
      readTimeout: 20
      db:     
        scenario: 6
        traces: 1
kind: ConfigMap
metadata:
  name: zk-scenario-manager
