apiVersion: v1
kind: Service
metadata:
  name: zk-scenario-manager
  labels:
    app: zk-scenario-manager
spec:
  selector:
    app: zk-scenario-manager
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
