server:
  host: localhost
  port: 80

logs:
  color: true
  level: DEBUG

http:
  debug: true

redis:
  host: 127.0.0.1
  port: 6379
  dbs:
    traces: 1
    scenarios: 6
  readTimeout: 20

postgres:
  host: "localhost"
  port: 5432
  user: "pl"
  password: "pl"
  dbname: "pl"
  max_connections: 5
  max_idle_connections: 5
  connection_max_lifetime_in_minutes: 10