# Purpose: This action is triggered manually and is meant for the case where
# the build happens through this action and the deployment is done through CLI
name: dev-build-push
on:
  workflow_dispatch:
    inputs:
      DOCKER_TAG:
        description: 'Docker Image Tag'
        required: true
        default: '0.0.9-helmtest'
      GKE_CLUSTER:
        description: 'Cluster Name'
        required: true
        default: 'devclient03'

jobs:
  deploy:
    runs-on: zk-self-hosted
    steps:
      - name: Checkout
        run: |-
          echo "hello"