name: migrations-build-push
on:
  workflow_call:
    inputs:
      VERSION:
        type: string
        default: 'latest'
      ENVIRONMENT:
        type: string
        default: 'poc'
      DOCKER_IDENTIFIER:
        type: string
        default: 'prod'
    secrets:
      GKE_SA_KEY:
        required: true
env:
  ENV: ${{ github.event.inputs.ENV }}
  DOCKER_TAG: ${{ github.event.inputs.DOCKER_TAG }}
  GOOS: ${{ vars.GOOS }}
  GOARCH: ${{ vars.GOARCH }}
  CGO_ENABLED: ${{ vars.CGO_ENABLED }}
  GKE_SA_KEY: ${{ secrets.GKE_SA_KEY }}
  DOCKER_REG: ${{ vars.DOCKER_REG }}
  PROJECT_ID: ${{ vars.PROJECT_ID }}
  DOCKER_REPO: ${{ vars.DOCKER_REPO }}
  MIGRATIONS_APP_NAME: ${{ vars.APP_NAME }}-migration
  GOPRIVATE: ${{ vars.GOPRIVATE }}
  TOKEN: ${{ secrets.GITPAT }}
  VERSION: ${{ inputs.VERSION }}
  ENVIRONMENT: ${{ inputs.ENVIRONMENT }}
  DOCKER_IDENTIFIER: ${{ inputs.DOCKER_IDENTIFIER }}

jobs:
  migrations-docker:
    environment:
      name: ${{ inputs.ENVIRONMENT }}
    runs-on: zk-self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ env.GKE_SA_KEY }}'

      - name: login to docker registry
        run: |
          gcloud auth configure-docker $DOCKER_REG --quiet
          
      - name: Docker build
        run: |-
          echo "DOCKER_TAG=$VERSION"
          docker build -f Dockerfile-Migration --tag "$DOCKER_REG/$PROJECT_ID/$DOCKER_REPO/$DOCKER_IDENTIFIER/$MIGRATIONS_APP_NAME:$GITHUB_SHA" .

      - name: Docker Tag
        run: |-
          echo "DOCKER_TAG=$VERSION"
          docker tag "$DOCKER_REG/$PROJECT_ID/$DOCKER_REPO/$DOCKER_IDENTIFIER/$MIGRATIONS_APP_NAME:$GITHUB_SHA" "$DOCKER_REG/$PROJECT_ID/$DOCKER_REPO/$DOCKER_IDENTIFIER/$MIGRATIONS_APP_NAME:$VERSION"

      - name: Docker push
        run: |-
          echo "DOCKER_TAG=$VERSION"
          docker push "$DOCKER_REG/$PROJECT_ID/$DOCKER_REPO/$DOCKER_IDENTIFIER/$MIGRATIONS_APP_NAME:$GITHUB_SHA"
          docker push "$DOCKER_REG/$PROJECT_ID/$DOCKER_REPO/$DOCKER_IDENTIFIER/$MIGRATIONS_APP_NAME:$VERSION"
